### ISSUE TITLE
GPL?

### ISSUE THREAD

**Issue by johnmay** [dan2097/jna-inchi#5]
Noel pointed me here, looks cool but any reason for the GPL, wouldn't a better option just be to use the InChI license?

**Comment by johnmay** [comment]
https://www.inchi-trust.org/download/104/LICENCE.pdf

**Comment by dan2097** [comment]
I'm trying to get this clarified with the InChI trust. The InChI trust license is very similar to the LGPL, but unfortunately is not a strict superset of its permissions. I'm unsure as to whether the copyleft parts apply considering the bindings are directly derived from the source code. My preference would be to license the project under the LGPL rather than a license almost noone has ever heard of. For the moment I've dual licensed it.

**Comment by johnmay** [comment]
If JNA is dynamically linking it could technically be BSD. Anyways I think dual licensing would be good, even EPAM are moving away from GPL right?

**Comment by dan2097** [comment]
The InChI trust are okay with this being under the LGPL, so the license going forward is the LGPL

**Comment by johnmay** [comment]
:+1:
